### ISSUE TITLE
Fail to download permutation graph file with urlretrieve

### ISSUE THREAD

**Issue by lingling93** [drugrelink/drugrelink#3]
The file is .json.bz2, it deprecates after downloaded.

**Comment by lingling93** [comment]
@cthoyt Here is one link of the permutation file.
https://github.com/dhimmel/integrate/blob/master/data/permuted/hetnet_perm-1.json.bz2

**Comment by cthoyt** [comment]
Probably closed with https://github.com/lingling93/comparison/commit/ef589df466a05ba2ef26b09028f12c2afb5f0409
